NUMBER_ENTITIES = [
    {
        "key": "heatingThermalProfileSeasonData.comfortTemperature",
        "name": "Heating Comfort Temperature",
        "translation_key": "heating_comfort_temperature",
        "min": 15,
        "max": 25,
        "step": 0.5,
    },
    {
        "key": "heatingThermalProfileSeasonData.kneePointTemperature",
        "name": "Heating Knee Point",
        "translation_key": "heating_knee_point",
        "min": 5,
        "max": 15,
        "step": 0.5,
    },
    {
        "key": "heatingThermalProfileSeasonData.reductionDeltaTemperature",
        "name": "Heating Reduction Delta",
        "translation_key": "heating_reduction_delta",
        "min": 0,
        "max": 5,
        "step": 0.5,
    },
    {
        "key": "coolingThermalProfileSeasonData.comfortTemperature",
        "name": "Cooling Comfort Temperature",
        "translation_key": "cooling_comfort_temperature",
        "min": 20,
        "max": 28,
        "step": 0.5,
    },
    {
        "key": "coolingThermalProfileSeasonData.kneePointTemperature",
        "name": "Cooling Knee Point",
        "translation_key": "cooling_knee_point",
        "min": 15,
        "max": 25,
        "step": 0.5,
    },
    {
        "key": "coolingThermalProfileSeasonData.temperatureLimit",
        "name": "Cooling Temperature Limit",
        "translation_key": "cooling_temperature_limit",
        "min": 20,
        "max": 28,
        "step": 0.5,
    },
    {
        "key": "temperature.manualTemperature",
        "name": "Manual Comfort Temperature",
        "translation_key": "manual_comfort_temperature",
        "min": 18,
        "max": 28,
        "step": 0.5,
    },
    {
        "key": "season.heatingThresholdTemperature",
        "name": "Heating Threshold",
        "translation_key": "heating_threshold",
        "min": 5,
        "max": 15,
        "step": 0.5,
    },
    {
        "key": "season.coolingThresholdTemperature",
        "name": "Cooling Threshold",
        "translation_key": "cooling_threshold",
        "min": 16,
        "max": 25,
        "step": 0.5,
    },
]

CONNECTED_DEVICE_NUMBER_PROPERTIES = {
    1: [
        {
            "property": "29/1/2",
            "name": "RMOT Heating Threshold",
            "translation_key": "rmot_heating_threshold",
            "min": 5,
            "max": 20,
            "step": 0.5,
            "unit": "°C",
            "faktor": 0.1,
            "byte_count": 2,
        },
        {
            "property": "29/1/3",
            "name": "RMOT Cooling Threshold",
            "translation_key": "rmot_cooling_threshold",
            "min": 5,
            "max": 35,
            "step": 0.5,
            "unit": "°C",
            "faktor": 0.1,
            "byte_count": 2,
        },
    ],
    20: [
        {
            "property": "23/1/4",
            "name": "Heatpump minimum temperature",
            "translation_key": "heatpump_min_temp",
            "min": 10,
            "max": 17,
            "step": 1,
            "unit": "°C",
            "faktor": 0.1,
            "byte_count": 2,
        },
        {
            "property": "23/1/3",
            "name": "Heatpump maximum temperature",
            "translation_key": "heatpump_max_temp",
            "min": 40,
            "max": 60,
            "step": 1,
            "unit": "°C",
            "faktor": 0.1,
            "byte_count": 2,
        },
    ],
}
