NUMBER_ENTITIES = [
    {
        "key": "heatingThermalProfileSeasonData.comfortTemperature",
        "name": "Heating Comfort Temperature",
        "translation_key": "heating_comfort_temperature",
        "min": 15,
        "max": 25,
        "step": 0.5,
    },
    {
        "key": "heatingThermalProfileSeasonData.kneePointTemperature",
        "name": "Heating Knee Point",
        "translation_key": "heating_knee_point",
        "min": 5,
        "max": 15,
        "step": 0.5,
    },
    {
        "key": "heatingThermalProfileSeasonData.reductionDeltaTemperature",
        "name": "Heating Reduction Delta",
        "translation_key": "heating_reduction_delta",
        "min": 0,
        "max": 5,
        "step": 0.5,
    },
    {
        "key": "coolingThermalProfileSeasonData.comfortTemperature",
        "name": "Cooling Comfort Temperature",
        "translation_key": "cooling_comfort_temperature",
        "min": 20,
        "max": 28,
        "step": 0.5,
    },
    {
        "key": "coolingThermalProfileSeasonData.kneePointTemperature",
        "name": "Cooling Knee Point",
        "translation_key": "cooling_knee_point",
        "min": 15,
        "max": 25,
        "step": 0.5,
    },
    {
        "key": "coolingThermalProfileSeasonData.temperatureLimit",
        "name": "Cooling Temperature Limit",
        "translation_key": "cooling_temperature_limit",
        "min": 20,
        "max": 28,
        "step": 0.5,
    },
    {
        "key": "temperature.manualTemperature",
        "name": "Manual Comfort Temperature",
        "translation_key": "manual_comfort_temperature",
        "min": 18,
        "max": 28,
        "step": 0.5,
    },
    {
        "key": "season.heatingThresholdTemperature",
        "name": "Heating Threshold",
        "translation_key": "heating_threshold",
        "min": 5,
        "max": 15,
        "step": 0.5,
    },
    {
        "key": "season.coolingThresholdTemperature",
        "name": "Cooling Threshold",
        "translation_key": "cooling_threshold",
        "min": 16,
        "max": 25,
        "step": 0.5,
    },
]
