#!/bin/bash

echo "==================================================================================="
echo "ComfoClime Tunnel Setup für Codespace"
echo "==================================================================================="
echo ""
echo "Da dein Codespace in der Cloud läuft, muss ein Tunnel zu deinem lokalen"
echo "ComfoClime-Gerät eingerichtet werden."
echo ""
echo "FÜHRE DIESEN BEFEHL AUF DEINEM LOKALEN RECHNER AUS:"
echo "==================================================================================="
echo ""
echo "gh codespace ssh -- -R 8080:DEINE_COMFOCLIME_IP:80"
echo ""
echo "Beispiel:"
echo "gh codespace ssh -- -R 8080:192.168.1.100:80"
echo "gh codespace ssh -- -R 8080:comfoclime.local:80"
echo ""
echo "==================================================================================="
echo ""
echo "Danach ist deine ComfoClime im Codespace unter folgender Adresse erreichbar:"
echo "  http://localhost:8080"
echo ""
echo "In Home Assistant kannst du dann diese Adresse verwenden:"
echo "  localhost:8080"
echo ""
echo "==================================================================================="
